before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
#  directories:
#    - node_modules
#    - frontend/node_modules
#    - build/npm
#    - $HOME/.npm
#    - $HOME/.gradle/caches/
#    - $HOME/.gradle/wrapper/
language: groovy
jdk:
  - openjdk8

# Skip the install step. Don't `go get` dependencies. Only build with the code
# in vendor/
install: true

# Don't email me the results of the test runs.
notifications:
  email: false

jobs:
  include:
    - stage: Tests
      script: ./gradlew clean integrationTest --tests "de.iteratec.osm.csi.**" && ./gradlew clean integrationTest --tests "de.iteratec.osm.report.**"  --tests "de.iteratec.osm.result.**"  --tests "de.iteratec.osm.measurement.**" 
    - stage: Tests
      script: ./gradlew -x jasmineRun test

