before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
dist: precise
cache:
  directories:
    - node_modules
    - frontend/node_modules
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
language: groovy
jdk:
  - openjdk8

# Skip the install step. Don't `go get` dependencies. Only build with the code
# in vendor/
install: true

# Don't email me the results of the test runs.
notifications:
  email: false

jobs:
  include:
    - stage: Tests
      script: ./gradlew integrationTest --tests de.**.* --full-stacktrace
    - stage: Tests
      script: ./gradlew -x jasmineRun test
    - stage: Tests
      install: skip
      script: date
#after_failure:
#  # dump the last 2000 lines of our build, and hope the error is in that!
#  - tail file:///home/travis/build/iteratec/OpenSpeedMonitor/build/test-results/integrationTest/index.html
