before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
installation: true
cache:
  directories:
    - node_modules
    - frontend/node_modules
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
language: groovy
jdk:
  - openjdk8
jobs:
  include:
    - stage: Tests
      script: ./gradlew integrationTest --tests de.**.* --full-stacktrace
    - stage: Tests
      script: ./gradlew -x jasmineRun test
    - stage: Tests
      script: date
#after_failure:
#  # dump the last 2000 lines of our build, and hope the error is in that!
#  - tail file:///home/travis/build/iteratec/OpenSpeedMonitor/build/test-results/integrationTest/index.html
